language: bash
services: docker

env:
  - VERSION=19
  - VERSION=20

install:
  - docker login -u "$USER_DOCKER_HUB" -p "$PASSWORD_DOCKER_HUB"

before_script:
  - env | sort
  - image="hashload/delphi-dev:${VERSION}"

script:
  - docker build -t $image .
    
after_script:
  - docker push $image
