language: bash
services: docker

env:
  - VERSION=tokyo
  - VERSION=rio

install:
  - docker login -u $USER_DOCKER_HUB -p $PASSWORD_DOCKER_HUB

before_script:
  - cd $VERSION
  - IMAGE="hashload/delphi-dev:$VERSION"

script:
  - docker build -t $IMAGE .
    
after_script:
  - docker push $IMAGE